_BASE_: "Base-SparseInst.yaml"
DATASETS:
  TRAIN: ("coco_seg_person_train",)
  TEST: ("coco_seg_person_train",)
INPUT:
  MAX_SIZE_TRAIN: 320
  MIN_SIZE_TRAIN: 
  - 320 #c256
MODEL:
  WEIGHTS: "/home/lujia/test/SparseInst-test/pretrained/mb_person.pth"
  BACKBONE:
    NAME: "build_mbv2_backbone"
  SPARSE_INST:
    ENCODER:
      IN_FEATURES: ["mb3", "mb4", "mb5"]
      # NUM_CHANNELS: 128
    DECODER:
      # GROUPS: 4
      NUM_CLASSES: 1
      # NUM_MASKS: 10
      # INST:
      #   CONVS: 2
      #   DIM: 128
      # KERNEL_DIM: 64
      # MASK:
      #   CONVS: 2
      #   DIM: 128
    # NUM_CLASSES: 1
  MBNET:
    NORM: "FrozenBN"
    OUT_FEATURES: ["mb3", "mb4", "mb5"]
SOLVER:
  BASE_LR: 5.0e-05 # 5.0e-05
  CHECKPOINT_PERIOD: 1800
  IMS_PER_BATCH: 128
  MAX_ITER: 30000
  WARMUP_ITERS: 1000
  STEPS: [10000, 20000]
TEST:
  EVAL_PERIOD: 300
OUTPUT_DIR: "output/sparse_inst_mbnetv2_person"
