_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "/home/lujia/test/SparseInst-main/pretrained/model_mb.pth"
  BACKBONE:
    NAME: "build_mbv2_backbone"
  SPARSE_INST:
    ENCODER:
      IN_FEATURES: ["mb3", "mb4", "mb5"]
  MBNET:
    NORM: "FrozenBN"
    OUT_FEATURES: ["mb3", "mb4", "mb5"]
OUTPUT_DIR: "output/sparse_inst_mbnetv2"